{% set name = "lzstring" %}
{% set version = "1.0.4" %}
{% set sha256 = "1afa61e598193fbcc211e0899f09a9679e33f9102bccc37fbfda0b7fef4d9ea2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1002
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - future

test:
  requires:
    - python {{ python_min }}
  imports:
    - lzstring

about:
  home: https://github.com/gkovacs/lz-string-python
  summary: 'lz-string for python'
  license: MIT
  license_family: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ewels
