# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "im9xWxJRXoeQAL6MQC7r8KMI7yoY+/IaXPozug73cdxJ+c3otZAhwU/cM3x/xanmNpiIylJw2ERe1rGIFdgRrK9rTzAnZcN810USn9TcuPq7nqK9oMZ//BNLHLa/DSonL4XQmQKfwUVuZ9XhjDJ8qaITJ+goF5RVtmeIq2sW8j3Hp390rVDlenjpecdqhzAR2PdwjJ9DWNkHwTnNZMphVpYbGX9efg1lxXPS5LLI1+GcPdPjZxaBhL0qWg9QQUuTdb39xJ0swXD668iOsE6M5ScwvAXr7pYG5Qr8XPpQQZgToFJ9VmOZ4jhkjkOLwIOfuP6WONkKZPXz2GXcWlhT6Ktc5loZ6sLBYrhpOhtCuPQbdoWCBXz3Pthe0eA9JCtS+wyvFSgChD5oj6Zx/bfyoevO5GjH58IGaOacLWLbVXthHOb66h42zi5DOW+nvr0uJ6h7wvDqjkd9u88AjhZzQbEiY2DU5G+5D0vj9ou2rn4DLOYLN2XVhXIF6FPdjmnKjQ1cfM0zFPTAkd1X9Z7T6oMSDxhtlwuL30CoOim1JqgB0lPDKBfSVVGKulQRby+enPJ4mZ52Kknl5KM9Ug1GLwAbESstJqLDfjp7N8Ol350IneDMiVI/LFC5PikSvphS90IyRpgWqcgGOWdiCd2eBuBMBx6v9ttdKGg9qWiVqVs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
