appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZL1daxIRbWt5VQOP5ZTdo/E2v+YW3uPL9XHtsbaKrO1+7nLpbM1VMuK7PdIY3p6sHMnt2/ROYVc9MnE3rQO0s3wBB7PV4HpgHU3fo3ConW0AcjsGrfRovjMKVaZNZnCXGrQRK+AGf46J0IS2ENDWCYvcM0kPHDoQziGq7VE7RZrlTVxooe7lH+NX6XZg3AW2KfAqi++go1c30K5mW27PaeJwxgLhuhHME1Gi5ycgWnGcgBgmpyslP5SEpp+i7yyopjaR8spN0UkH3fTByD3aLl17o145xSTQTOkNgPEhwhEaw5wU8acMTIdLeOTissqU1l2s6UpuN7ofA7TzTVVruSZZlMGgEZRQBEZBq+6MYVPE8BevPuxlsDwWXPTV324Z5cQe330vVjHsLwyIJJfGY+/rymp5yx6jrARkwmUKF3161i7Rf36oCUzrh9pRpVtiXVJn76Jm4uHO3VsownjkxnDgBbGTY+86xzoJgiLZlqMAnS0FrtfZopHUDK3dah53/FDQFM+Ir+KOHGu5qh4cQvsOumTtUi8FAvoPOlFWsldb8Mag1ArKj+5+qV20KsgMogfa5smyH34UbBM8jitSyKVAg/J63lmvNpRkayyHHwBTqAItk+rX7ujQqO6Q7cLZTLMS60JSWbKehGqPLrp73vbNaTFZMQSJxO7rlK5nMkc=}
