travis:
  secure:
    BINSTAR_TOKEN: im9xWxJRXoeQAL6MQC7r8KMI7yoY+/IaXPozug73cdxJ+c3otZAhwU/cM3x/xanmNpiIylJw2ERe1rGIFdgRrK9rTzAnZcN810USn9TcuPq7nqK9oMZ//BNLHLa/DSonL4XQmQKfwUVuZ9XhjDJ8qaITJ+goF5RVtmeIq2sW8j3Hp390rVDlenjpecdqhzAR2PdwjJ9DWNkHwTnNZMphVpYbGX9efg1lxXPS5LLI1+GcPdPjZxaBhL0qWg9QQUuTdb39xJ0swXD668iOsE6M5ScwvAXr7pYG5Qr8XPpQQZgToFJ9VmOZ4jhkjkOLwIOfuP6WONkKZPXz2GXcWlhT6Ktc5loZ6sLBYrhpOhtCuPQbdoWCBXz3Pthe0eA9JCtS+wyvFSgChD5oj6Zx/bfyoevO5GjH58IGaOacLWLbVXthHOb66h42zi5DOW+nvr0uJ6h7wvDqjkd9u88AjhZzQbEiY2DU5G+5D0vj9ou2rn4DLOYLN2XVhXIF6FPdjmnKjQ1cfM0zFPTAkd1X9Z7T6oMSDxhtlwuL30CoOim1JqgB0lPDKBfSVVGKulQRby+enPJ4mZ52Kknl5KM9Ug1GLwAbESstJqLDfjp7N8Ol350IneDMiVI/LFC5PikSvphS90IyRpgWqcgGOWdiCd2eBuBMBx6v9ttdKGg9qWiVqVs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
