travis:
  secure:
    BINSTAR_TOKEN: HrmAhJvZPM/48VSRrGjxL4LMOHT4rYkXbS5TLSzPdNhcBb4gXfQB9CuptBFTXB6KI3ChTfH235cu5SdrzP1ufnoetPmalULIythSAdsm4LFG/7c+6HN5zNQqbS2SX+h3a6VJ22APnj3ae9PO4brhBa6zmPX8kMAH2NY9I5VOefdsIhqJlYP4YSbtxKiGZmI4U6M95ka1aV11XCc+T1MXS+63KxNbAruTuwoNvoCiuZDypDf3O1bYD3b5mrl1J0zKhnDaSPHHxTWY7l7+8ub/odCzNMxaRIvE4qf51SKHCFGLuo9lLkhUFiP9xlah5EKigUCml/NegozJLsyK1zeXC2Y2U72BIdkLCrk6jtRf/8bVZ6nDEE5IAHB/ubKgKTf/OtE5BbvNGQo1CJulyEx9/eUkFEXM4EEgoIraTU7402AC9hXElzVhFZbTSMCbX5zp2sqxo/bLHqTACnWF2LKzvf2/csUcB79BBnE8DWesLvdnMT2GGN7cX1tSc8OkvJx4Ch0pMBbnSS4fSyDIu7M9qTQ4V60hBqBTz9QyAXFGVXiHSvDJa+JqycNmtXwqMAE7eFHNks2czZu5BL+9Stt+XkZpEKVOvDzwak6LIpdejnl6ypoqHIRLDakaMxKWxcYH1SHG+qZFjgrl1N+LEcQvccJkkkDx7QnrEw/8QRNA1ds=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
